### ISSUE TITLE
Add support for "no unit" type

### ISSUE THREAD

**Issue by bladan** [bernedom/SI#41]
Altough we could use standard C++ variable types such as double or int, a "no unit" type could be useful:
- To show the user we are using SI for a given class/calculation
- For "unitless" constants, often seen in physics formulas
- Literals for % or  ‰ with \<ratio\>

**Comment by bernedom** [comment]
Decided not to implement this. Scalars without a type should be exactly that, so wrapping them artificially does somehow defeat the purpose of SI being transparent with standard types. 
C++20 will bring us mathematical constants as library function so wrapping this might break future compatibility. 
As for percentage since % is not allowed in the literal this would be quite difficult to achieve
